version: '3.7'

services:

    nginx:
        build:
            context: ./docker/nginx
        ports:
            - "80:8083"
        volumes:
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
            - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
            - .:/var/www/html
        user: user
        networks:
            - backend
        links:
            - php
            - mysql

    php:
        build:
            context: ./docker/php
        image: 'laravelapp'
        volumes:
            - .:/var/www/html
            - ./docker/php/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
            - ./docker/php/error_reporting.ini:/usr/local/etc/php/conf.d/error_reporting.ini
            - /home/shaevmv/.ssh/id_rsa.pub:/home/user/.ssh/id_rsa.pub
        user: user
        networks:
            - backend

    redis:
        build: ./docker/redis
        container_name: redis
        command: redis-server --appendonly yes
        volumes:
            - ./docker/redis/data:/data
        ports:
            - "8002:6379"
        networks:
            - backend

    mysql:
        image: mysql:8
        ports:
            - "3306:3306"
        environment:
            MYSQL_DATABASE: 'avangard'
            MYSQL_ROOT_PASSWORD: 'secret'
            MYSQL_USER: 'default'
            MYSQL_PASSWORD: 'secret'
            MYSQL_ALLOW_EMPTY_PASSWORD: 1
        volumes:
            - ./docker/mysql/db:/var/lib/mysql
        networks:
            - backend

    rabbitmq:
        image: rabbitmq:3.9-management
        container_name: rabbitmq-avangard
        ports:
            - "15672:15672"
        networks:
            backend:
                aliases:
                    - rabbitmq

networks:
    backend:
        driver: bridge
